[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.build]
cmds = [
  'npm ci --only=production',
  'cd backend && npm ci --only=production'
]

[phases.start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production'